pipewire_flow_sources = files(
  'pwf_log.c',
  'pwf_pw_core.c',
  'pwf_spa_format.c',
  'pwf_stream.c',
  'pwf_stream_playback.c',
  'pwf_stream_routing.c',
  'pwf_buffer.c',
  'pwf_audio_format.c',
  'pwf_video_format.c',
  'pwf_video_enum.c',
  'pwf_filter.c',
  'pwf_filter_port.c',
  'pwf_filter_process.c',
  'pwf_filter_event.c',
  'pwf_filter_dmabuf.c',
  'pwf_filter_port_link.c',
  'pwf_dmabuf.c',
  'pwf_rate_limit.c',
  'pwf_stream_dmabuf.c',
)

pipewire_flow_lib = library('pipewire-flow',
  pipewire_flow_sources,
  include_directories: pwf_inc,
  dependencies: [pipewire_dep, dependency('threads')],
  gnu_symbol_visibility: 'hidden',
  soversion: meson.project_version().split('.')[0],
  install: true,
)
